name: spikingtsf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=1.13.0
      - torchvision
      - numpy
      - pandas
      - tables
      - scikit-learn
      - scipy
      - matplotlib
      - timm
      - spikingjelly==0.0.0.0.14
      - tqdm
      - optuna
      - PyYAML
      - requests
      - Jinja2
      - pillow
